USER_TABLE = "users"

USER_TABLE_USERNAME_COLUMN = "username"
USER_TABLE_USERNAME_COLUMN_DEFINITION = "TEXT PRIMARY KEY"

USER_TABLE_PASSWORD_COLUMN = "password"
USER_TABLE_PASSWORD_COLUMN_DEFINITION = "TEXT NOT NULL"

USER_TABLE_EVENTIM_EMAIL_COLUMN = "eventimEmail"
USER_TABLE_EVENTIM_EMAIL_COLUMN_DEFINITION = "TEXT NOT NULL UNIQUE"

USER_TABLE_EVENTIM_PASSWORD_COLUMN = "eventimPassword"
USER_TABLE_EVENTIM_PASSWORD_COLUMN_DEFINITION = "TEXT"