USER_TABLE = "users"

USER_TABLE_EMAIL_COLUMN = "email"
USER_TABLE_EMAIL_COLUMN_DEFINITION = "TEXT PRIMARY KEY"

USER_TABLE_PASSWORD_COLUMN = "password"
USER_TABLE_PASSWORD_COLUMN_DEFINITION = "TEXT"



EVENT_TABLE = "events"

EVENT_TABLE_NAME_COLUMN = "name"
EVENT_TABLE_NAME_COLUMN_DEFINITION = "TEXT"

EVENT_TABLE_TYPE_COLUMN = "type"
EVENT_TABLE_TYPE_COLUMN_DEFINITION = "TEXT"

EVENT_TABLE_LOCATION_COLUMN = "location"
EVENT_TABLE_LOCATION_COLUMN_DEFINITION = "TEXT"

EVENT_TABLE_DATE_COLUMN = "date"
EVENT_TABLE_DATE_COLUMN_DEFINITION = "TEXT"

EVENT_TABLE_TIME_COLUMN = "time"
EVENT_TABLE_TIME_COLUMN_DEFINITION = "TEXT"

EVENT_TABLE_PRICE_COLUMN = "price"
EVENT_TABLE_PRICE_COLUMN_DEFINITION = "TEXT"

EVENT_TABLE_AVAILABILITY_COLUMN = "availability"
EVENT_TABLE_AVAILABILITY_COLUMN_DEFINITION = "TEXT"



PREFERENCE_TABLE = "preferences"

PREFERENCE_TABLE_TYPES_COLUMN = "types"
PREFERENCE_TABLE_TYPES_COLUMN_DEFINITION = "TEXT"

PREFERENCE_TABLE_DATES_COLUMN = "dates"
PREFERENCE_TABLE_DATES_COLUMN_DEFINITION = "TEXT"

PREFERENCE_TABLE_HOURS_COLUMN = "hours"
PREFERENCE_TABLE_HOURS_COLUMN_DEFINITION = "TEXT"

PREFERENCE_TABLE_TICKET_COUNT_COLUMN = "ticketCount"
PREFERENCE_TABLE_TICKET_COUNT_COLUMN_DEFINITION = "TEXT"

PREFERENCE_TABLE_MIN_PRICE_COLUMN = "minPrice"
PREFERENCE_TABLE_MIN_PRICE_COLUMN_DEFINITION = "TEXT"

PREFERENCE_TABLE_MAX_PRICE_COLUMN = "maxPrice"
PREFERENCE_TABLE_MAX_PRICE_COLUMN_DEFINITION = "TEXT"